# Generated by Django 5.0.7 on 2024-09-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0004_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='is_registed',
            field=models.BooleanField(default=False),
        ),
    ]
