# Generated by Django 5.0.7 on 2024-09-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_service', '0005_courseregistration_is_registed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregistration',
            old_name='is_registed',
            new_name='is_registered',
        ),
    ]
